---
- name: Generate random temp directory
  command: mktemp -d "{{ percona_repo_temp_directory_mask }}"
  become: no
  delegate_to: localhost
  changed_when: false
  register: percona_repo_temp_dir

- name: Download Percona Repo DEB file
  get_url:
    url: "{{ percona_repo_url }}"
    dest: "{{ percona_repo_temp_dir.stdout }}"
    mode: '0644'
  become: no
  delegate_to: localhost
  changed_when: false

- name: Copy DEB file to target host
  copy:
    src: "{{ percona_repo_temp_dir.stdout + '/' + percona_repo_deb_file }}"
    dest: /tmp/
    force: yes
    owner: root
    group: root
    mode: '0400'
  changed_when: false

- name: Add Percona APT Repository
  apt:
    deb: /tmp/{{ percona_repo_deb_file }}
  register: percona_repo_added
