---
- name: Ensure ca-certificates package is present
  apt:
    name: ca-certificates
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Add Percona APT Repository
  apt:
    deb: "{{ percona_repo_url }}"
  register: percona_repo_added
