---
- name: Ensure ca-certificates package is present
  apt:
    name: ca-certificates
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Add Percona APT Repository
  apt:
    deb: https://repo.percona.com/apt/percona-release_{{ percona_repo_version }}-{{ percona_repo_review }}.{{ ansible_distribution_release | lower }}_all.deb
  register: percona_repo_added

- name: Update APT cache
  apt:
    update_cache: yes
  when: percona_repo_added | changed
